// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const DevMessage = __t.object("DevMessage", {
  id: __t.u64(),
  sender: __t.string(),
  recipient: __t.string(),
  taskId: __t.string(),
  body: __t.string(),
  createdAt: __t.timestamp(),
});
export type DevMessage = __Infer<typeof DevMessage>;

export const DevTask = __t.object("DevTask", {
  id: __t.string(),
  title: __t.string(),
  details: __t.string(),
  area: __t.string(),
  status: __t.string(),
  createdBy: __t.string(),
  assignee: __t.string(),
  dependsOn: __t.string(),
  result: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type DevTask = __Infer<typeof DevTask>;

export const FileLock = __t.object("FileLock", {
  path: __t.string(),
  holder: __t.string(),
  taskId: __t.string(),
  reason: __t.string(),
  acquiredAt: __t.timestamp(),
  expiresAt: __t.timestamp(),
});
export type FileLock = __Infer<typeof FileLock>;

export const Session = __t.object("Session", {
  name: __t.string(),
  tool: __t.string(),
  focus: __t.string(),
  lastSeen: __t.timestamp(),
});
export type Session = __Infer<typeof Session>;

