// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  sourceId: __t.string().name("source_id"),
  symbol: __t.string(),
  metric: __t.string(),
  value: __t.string(),
  unit: __t.string(),
  period: __t.string(),
  quality: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
