// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  accountId: __t.string().name("account_id"),
  accountStatus: __t.string().name("account_status"),
  cash: __t.string(),
  buyingPower: __t.string().name("buying_power"),
  equity: __t.string(),
  dailyPnl: __t.option(__t.string()).name("daily_pnl"),
  positionsJson: __t.string().name("positions_json"),
  openOrdersJson: __t.string().name("open_orders_json"),
  capturedAt: __t.timestamp().name("captured_at"),
});
