// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  proposalId: __t.string().primaryKey().name("proposal_id"),
  approver: __t.identity(),
  riskDecisionId: __t.string().name("risk_decision_id"),
  approvedAt: __t.timestamp().name("approved_at"),
});
