// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  runId: __t.string().name("run_id"),
  thesisId: __t.string().name("thesis_id"),
  quoteId: __t.string().name("quote_id"),
  critiqueRefs: __t.string().name("critique_refs"),
  model: __t.string(),
  promptVersion: __t.string().name("prompt_version"),
  policyVersion: __t.string().name("policy_version"),
  maxOrderNotional: __t.string().name("max_order_notional"),
  capturedAt: __t.timestamp().name("captured_at"),
});
