// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  runId: __t.string().name("run_id"),
  workId: __t.string().name("work_id"),
  actor: __t.identity(),
  model: __t.string(),
  promptVersion: __t.string().name("prompt_version"),
  inputRefs: __t.string().name("input_refs"),
  status: __t.string(),
  reservedTokens: __t.u32().name("reserved_tokens"),
  tokensUsed: __t.u32().name("tokens_used"),
  startedAt: __t.timestamp().name("started_at"),
  expiresAt: __t.timestamp().name("expires_at"),
  actualModel: __t.string().name("actual_model"),
  outputJson: __t.string().name("output_json"),
  pricingVersion: __t.string().name("pricing_version"),
  reservedInputTokens: __t.u32().name("reserved_input_tokens"),
  reservedOutputTokens: __t.u32().name("reserved_output_tokens"),
  inputTokens: __t.u32().name("input_tokens"),
  cacheReadTokens: __t.u32().name("cache_read_tokens"),
  cacheWriteTokens: __t.u32().name("cache_write_tokens"),
  outputTokens: __t.u32().name("output_tokens"),
  reservedSpendMicros: __t.u64().name("reserved_spend_micros"),
  spendMicros: __t.u64().name("spend_micros"),
  failureReason: __t.string().name("failure_reason"),
});
