// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  runId: __t.string().name("run_id"),
  taskId: __t.string().name("task_id"),
  sender: __t.identity(),
  kind: __t.string(),
  body: __t.string(),
  evidenceRef: __t.string().name("evidence_ref"),
  createdAt: __t.timestamp().name("created_at"),
  symbol: __t.string(),
  recipientRole: __t.string().name("recipient_role"),
});
