// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  snapshotId: __t.string().name("snapshot_id"),
  symbol: __t.string(),
  feed: __t.string(),
  bidPrice: __t.string().name("bid_price"),
  bidSize: __t.string().name("bid_size"),
  askPrice: __t.string().name("ask_price"),
  askSize: __t.string().name("ask_size"),
  asOf: __t.timestamp().name("as_of"),
  capturedAt: __t.timestamp().name("captured_at"),
});
