// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  accountId: __t.string().primaryKey().name("account_id"),
  isOpen: __t.bool().name("is_open"),
  asOf: __t.timestamp().name("as_of"),
  capturedAt: __t.timestamp().name("captured_at"),
});
