// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  orderId: __t.string().primaryKey().name("order_id"),
  requestedBy: __t.identity().name("requested_by"),
  reason: __t.string(),
  status: __t.string(),
  detail: __t.string(),
  requestedAt: __t.timestamp().name("requested_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
