// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  proposalId: __t.string().name("proposal_id"),
  clientOrderId: __t.string().name("client_order_id"),
  alpacaOrderId: __t.string().name("alpaca_order_id"),
  status: __t.string(),
  submittedAt: __t.timestamp().name("submitted_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
