// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  runId: __t.string().primaryKey().name("run_id"),
  policyId: __t.string().name("policy_id"),
  maxInferences: __t.u32().name("max_inferences"),
  maxTokens: __t.u32().name("max_tokens"),
  maxConcurrent: __t.u32().name("max_concurrent"),
  maxAttempts: __t.u32().name("max_attempts"),
  usedInferences: __t.u32().name("used_inferences"),
  usedTokens: __t.u32().name("used_tokens"),
});
