// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  proposalId: __t.string().name("proposal_id"),
  reviewer: __t.identity(),
  policyVersion: __t.string().name("policy_version"),
  outcome: __t.string(),
  checks: __t.string(),
  decidedAt: __t.timestamp().name("decided_at"),
  expiresAt: __t.timestamp().name("expires_at"),
  policyId: __t.string().name("policy_id"),
  snapshotId: __t.string().name("snapshot_id"),
  quoteId: __t.string().name("quote_id"),
});
