// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  orderId: __t.string().name("order_id"),
  alpacaOrderId: __t.string().name("alpaca_order_id"),
  event: __t.string(),
  brokerStatus: __t.string().name("broker_status"),
  executionId: __t.string().name("execution_id"),
  brokerTimestamp: __t.timestamp().name("broker_timestamp"),
  receivedAt: __t.timestamp().name("received_at"),
});
