// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  runId: __t.string().name("run_id"),
  symbol: __t.string(),
  kind: __t.string(),
  objective: __t.string(),
  status: __t.string(),
  assignee: __t.option(__t.identity()),
  leaseUntil: __t.option(__t.timestamp()).name("lease_until"),
  version: __t.u64(),
  result: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
  role: __t.string(),
  dependsOn: __t.string().name("depends_on"),
});
