// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.string(),
  proposalId: __t.string(),
  policyVersion: __t.string(),
  outcome: __t.string(),
  checks: __t.string(),
  expiresAt: __t.timestamp(),
  snapshotId: __t.string(),
  clockAsOf: __t.timestamp(),
};
