// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.string(),
  runId: __t.string(),
  thesisId: __t.string(),
  quoteId: __t.string(),
  critiqueRefs: __t.string(),
  model: __t.string(),
  promptVersion: __t.string(),
  policyVersion: __t.string(),
  maxOrderNotional: __t.string(),
};
