// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.string(),
  snapshotId: __t.string(),
  symbol: __t.string(),
  feed: __t.string(),
  bidPrice: __t.string(),
  bidSize: __t.string(),
  askPrice: __t.string(),
  askSize: __t.string(),
  asOf: __t.timestamp(),
};
