// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  runId: __t.string().name("run_id"),
  symbol: __t.string(),
  kind: __t.string(),
  uri: __t.string(),
  asOf: __t.timestamp().name("as_of"),
  retrievedAt: __t.timestamp().name("retrieved_at"),
  checksum: __t.string(),
  artifactRef: __t.string().name("artifact_ref"),
});
