// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  runId: __t.string().name("run_id"),
  symbol: __t.string(),
  author: __t.identity(),
  bullCase: __t.string().name("bull_case"),
  bearCase: __t.string().name("bear_case"),
  assumptions: __t.string(),
  invalidation: __t.string(),
  evidenceRefs: __t.string().name("evidence_refs"),
  createdAt: __t.timestamp().name("created_at"),
});
