// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  runId: __t.string().name("run_id"),
  thesisId: __t.string().name("thesis_id"),
  symbol: __t.string(),
  side: __t.string(),
  quantity: __t.string(),
  orderType: __t.string().name("order_type"),
  limitPrice: __t.string().name("limit_price"),
  status: __t.string(),
  proposedBy: __t.identity().name("proposed_by"),
  createdAt: __t.timestamp().name("created_at"),
});
