// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AccountAccess = __t.object("AccountAccess", {
  id: __t.string(),
  identity: __t.identity(),
  accountId: __t.string(),
});
export type AccountAccess = __Infer<typeof AccountAccess>;

export const AccountCheck = __t.object("AccountCheck", {
  accountId: __t.string(),
  status: __t.string(),
  details: __t.string(),
  checkedAt: __t.timestamp(),
});
export type AccountCheck = __Infer<typeof AccountCheck>;

export const AccountLedger = __t.object("AccountLedger", {
  accountId: __t.string(),
  cash: __t.string(),
  positionsJson: __t.string(),
  createdAt: __t.timestamp(),
});
export type AccountLedger = __Infer<typeof AccountLedger>;

export const AccountSnapshot = __t.object("AccountSnapshot", {
  id: __t.string(),
  accountId: __t.string(),
  accountStatus: __t.string(),
  cash: __t.string(),
  buyingPower: __t.string(),
  equity: __t.string(),
  positionsJson: __t.string(),
  openOrdersJson: __t.string(),
  capturedAt: __t.timestamp(),
});
export type AccountSnapshot = __Infer<typeof AccountSnapshot>;

export const Agent = __t.object("Agent", {
  identity: __t.identity(),
  role: __t.string(),
  status: __t.string(),
  lastSeen: __t.timestamp(),
});
export type Agent = __Infer<typeof Agent>;

export const Approval = __t.object("Approval", {
  proposalId: __t.string(),
  approver: __t.identity(),
  riskDecisionId: __t.string(),
  approvedAt: __t.timestamp(),
});
export type Approval = __Infer<typeof Approval>;

export const Decision = __t.object("Decision", {
  id: __t.string(),
  thesisId: __t.string(),
  reviewer: __t.identity(),
  outcome: __t.string(),
  rationale: __t.string(),
  createdAt: __t.timestamp(),
});
export type Decision = __Infer<typeof Decision>;

export const DecisionInput = __t.object("DecisionInput", {
  id: __t.string(),
  runId: __t.string(),
  thesisId: __t.string(),
  quoteId: __t.string(),
  critiqueRefs: __t.string(),
  model: __t.string(),
  promptVersion: __t.string(),
  policyVersion: __t.string(),
  maxOrderNotional: __t.string(),
  capturedAt: __t.timestamp(),
});
export type DecisionInput = __Infer<typeof DecisionInput>;

export const Fact = __t.object("Fact", {
  id: __t.string(),
  sourceId: __t.string(),
  symbol: __t.string(),
  metric: __t.string(),
  value: __t.string(),
  unit: __t.string(),
  period: __t.string(),
  quality: __t.string(),
  createdAt: __t.timestamp(),
});
export type Fact = __Infer<typeof Fact>;

export const Fill = __t.object("Fill", {
  id: __t.string(),
  orderId: __t.string(),
  alpacaActivityId: __t.string(),
  quantity: __t.string(),
  price: __t.string(),
  filledAt: __t.timestamp(),
});
export type Fill = __Infer<typeof Fill>;

export const InferenceAttempt = __t.object("InferenceAttempt", {
  id: __t.string(),
  runId: __t.string(),
  workId: __t.string(),
  actor: __t.identity(),
  model: __t.string(),
  promptVersion: __t.string(),
  inputRefs: __t.string(),
  status: __t.string(),
  reservedTokens: __t.u32(),
  tokensUsed: __t.u32(),
  startedAt: __t.timestamp(),
  expiresAt: __t.timestamp(),
  actualModel: __t.string(),
  outputJson: __t.string(),
});
export type InferenceAttempt = __Infer<typeof InferenceAttempt>;

export const MarketClock = __t.object("MarketClock", {
  accountId: __t.string(),
  isOpen: __t.bool(),
  asOf: __t.timestamp(),
  capturedAt: __t.timestamp(),
});
export type MarketClock = __Infer<typeof MarketClock>;

export const MarketObservation = __t.object("MarketObservation", {
  id: __t.string(),
  snapshotId: __t.string(),
  symbol: __t.string(),
  feed: __t.string(),
  bidPrice: __t.string(),
  bidSize: __t.string(),
  askPrice: __t.string(),
  askSize: __t.string(),
  asOf: __t.timestamp(),
  capturedAt: __t.timestamp(),
});
export type MarketObservation = __Infer<typeof MarketObservation>;

export const MarketObservationInput = __t.object("MarketObservationInput", {
  id: __t.string(),
  symbol: __t.string(),
  feed: __t.string(),
  bidPrice: __t.string(),
  bidSize: __t.string(),
  askPrice: __t.string(),
  askSize: __t.string(),
  asOf: __t.timestamp(),
});
export type MarketObservationInput = __Infer<typeof MarketObservationInput>;

export const Message = __t.object("Message", {
  id: __t.string(),
  runId: __t.string(),
  taskId: __t.string(),
  sender: __t.identity(),
  kind: __t.string(),
  body: __t.string(),
  evidenceRef: __t.string(),
  createdAt: __t.timestamp(),
  symbol: __t.string(),
  recipientRole: __t.string(),
});
export type Message = __Infer<typeof Message>;

export const MyAccountCheck = __t.object("MyAccountCheck", {});
export type MyAccountCheck = __Infer<typeof MyAccountCheck>;

export const MyAccountLedger = __t.object("MyAccountLedger", {});
export type MyAccountLedger = __Infer<typeof MyAccountLedger>;

export const MyAccountSnapshot = __t.object("MyAccountSnapshot", {});
export type MyAccountSnapshot = __Infer<typeof MyAccountSnapshot>;

export const MyAgent = __t.object("MyAgent", {});
export type MyAgent = __Infer<typeof MyAgent>;

export const MyAgentDirectory = __t.object("MyAgentDirectory", {});
export type MyAgentDirectory = __Infer<typeof MyAgentDirectory>;

export const MyApproval = __t.object("MyApproval", {});
export type MyApproval = __Infer<typeof MyApproval>;

export const MyDecision = __t.object("MyDecision", {});
export type MyDecision = __Infer<typeof MyDecision>;

export const MyDecisionInput = __t.object("MyDecisionInput", {});
export type MyDecisionInput = __Infer<typeof MyDecisionInput>;

export const MyFact = __t.object("MyFact", {});
export type MyFact = __Infer<typeof MyFact>;

export const MyFill = __t.object("MyFill", {});
export type MyFill = __Infer<typeof MyFill>;

export const MyInferenceAttempt = __t.object("MyInferenceAttempt", {});
export type MyInferenceAttempt = __Infer<typeof MyInferenceAttempt>;

export const MyMarketClock = __t.object("MyMarketClock", {});
export type MyMarketClock = __Infer<typeof MyMarketClock>;

export const MyMarketObservation = __t.object("MyMarketObservation", {});
export type MyMarketObservation = __Infer<typeof MyMarketObservation>;

export const MyMessage = __t.object("MyMessage", {});
export type MyMessage = __Infer<typeof MyMessage>;

export const MyPaperOrder = __t.object("MyPaperOrder", {});
export type MyPaperOrder = __Infer<typeof MyPaperOrder>;

export const MyPaperSubmission = __t.object("MyPaperSubmission", {});
export type MyPaperSubmission = __Infer<typeof MyPaperSubmission>;

export const MyReconciliation = __t.object("MyReconciliation", {});
export type MyReconciliation = __Infer<typeof MyReconciliation>;

export const MyRiskDecision = __t.object("MyRiskDecision", {});
export type MyRiskDecision = __Infer<typeof MyRiskDecision>;

export const MyRiskDecisionHistory = __t.object("MyRiskDecisionHistory", {});
export type MyRiskDecisionHistory = __Infer<typeof MyRiskDecisionHistory>;

export const MyRiskPolicy = __t.object("MyRiskPolicy", {});
export type MyRiskPolicy = __Infer<typeof MyRiskPolicy>;

export const MyRiskReservation = __t.object("MyRiskReservation", {});
export type MyRiskReservation = __Infer<typeof MyRiskReservation>;

export const MyRun = __t.object("MyRun", {});
export type MyRun = __Infer<typeof MyRun>;

export const MyRunConfig = __t.object("MyRunConfig", {});
export type MyRunConfig = __Infer<typeof MyRunConfig>;

export const MyRunMetric = __t.object("MyRunMetric", {});
export type MyRunMetric = __Infer<typeof MyRunMetric>;

export const MySource = __t.object("MySource", {});
export type MySource = __Infer<typeof MySource>;

export const MyTask = __t.object("MyTask", {});
export type MyTask = __Infer<typeof MyTask>;

export const MyThesis = __t.object("MyThesis", {});
export type MyThesis = __Infer<typeof MyThesis>;

export const MyTradeProposal = __t.object("MyTradeProposal", {});
export type MyTradeProposal = __Infer<typeof MyTradeProposal>;

export const OwnerConfig = __t.object("OwnerConfig", {
  key: __t.string(),
  owner: __t.identity(),
});
export type OwnerConfig = __Infer<typeof OwnerConfig>;

export const PaperOrder = __t.object("PaperOrder", {
  id: __t.string(),
  proposalId: __t.string(),
  clientOrderId: __t.string(),
  alpacaOrderId: __t.string(),
  status: __t.string(),
  submittedAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type PaperOrder = __Infer<typeof PaperOrder>;

export const PaperSubmission = __t.object("PaperSubmission", {
  id: __t.string(),
  orderId: __t.string(),
  actor: __t.identity(),
  attempt: __t.u32(),
  status: __t.string(),
  details: __t.string(),
  startedAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type PaperSubmission = __Infer<typeof PaperSubmission>;

export const Reconciliation = __t.object("Reconciliation", {
  id: __t.string(),
  status: __t.string(),
  details: __t.string(),
  capturedAt: __t.timestamp(),
  accountId: __t.string(),
});
export type Reconciliation = __Infer<typeof Reconciliation>;

export const RiskDecision = __t.object("RiskDecision", {
  id: __t.string(),
  proposalId: __t.string(),
  reviewer: __t.identity(),
  policyVersion: __t.string(),
  outcome: __t.string(),
  checks: __t.string(),
  decidedAt: __t.timestamp(),
  expiresAt: __t.timestamp(),
  policyId: __t.string(),
  snapshotId: __t.string(),
  quoteId: __t.string(),
});
export type RiskDecision = __Infer<typeof RiskDecision>;

export const RiskDecisionHistory = __t.object("RiskDecisionHistory", {
  id: __t.string(),
  proposalId: __t.string(),
  reviewer: __t.identity(),
  policyVersion: __t.string(),
  outcome: __t.string(),
  checks: __t.string(),
  decidedAt: __t.timestamp(),
  expiresAt: __t.timestamp(),
  policyId: __t.string(),
  snapshotId: __t.string(),
  quoteId: __t.string(),
});
export type RiskDecisionHistory = __Infer<typeof RiskDecisionHistory>;

export const RiskPolicy = __t.object("RiskPolicy", {
  id: __t.string(),
  runId: __t.string(),
  accountId: __t.string(),
  policyJson: __t.string(),
  createdAt: __t.timestamp(),
});
export type RiskPolicy = __Infer<typeof RiskPolicy>;

export const RiskReservation = __t.object("RiskReservation", {
  proposalId: __t.string(),
  accountId: __t.string(),
  quantity: __t.string(),
  notional: __t.string(),
  clientOrderId: __t.string(),
});
export type RiskReservation = __Infer<typeof RiskReservation>;

export const Run = __t.object("Run", {
  id: __t.string(),
  goal: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp(),
});
export type Run = __Infer<typeof Run>;

export const RunAccess = __t.object("RunAccess", {
  id: __t.string(),
  identity: __t.identity(),
  runId: __t.string(),
});
export type RunAccess = __Infer<typeof RunAccess>;

export const RunConfig = __t.object("RunConfig", {
  runId: __t.string(),
  policyId: __t.string(),
  maxInferences: __t.u32(),
  maxTokens: __t.u32(),
  maxConcurrent: __t.u32(),
  maxAttempts: __t.u32(),
  usedInferences: __t.u32(),
  usedTokens: __t.u32(),
});
export type RunConfig = __Infer<typeof RunConfig>;

export const RunMetric = __t.object("RunMetric", {
  id: __t.string(),
  runId: __t.string(),
  name: __t.string(),
  value: __t.string(),
  observedAt: __t.timestamp(),
});
export type RunMetric = __Infer<typeof RunMetric>;

export const Source = __t.object("Source", {
  id: __t.string(),
  runId: __t.string(),
  symbol: __t.string(),
  kind: __t.string(),
  uri: __t.string(),
  asOf: __t.timestamp(),
  retrievedAt: __t.timestamp(),
  checksum: __t.string(),
  artifactRef: __t.string(),
});
export type Source = __Infer<typeof Source>;

export const Task = __t.object("Task", {
  id: __t.string(),
  runId: __t.string(),
  symbol: __t.string(),
  kind: __t.string(),
  objective: __t.string(),
  status: __t.string(),
  assignee: __t.option(__t.identity()),
  leaseUntil: __t.option(__t.timestamp()),
  version: __t.u64(),
  result: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  role: __t.string(),
  dependsOn: __t.string(),
});
export type Task = __Infer<typeof Task>;

export const TaskLease = __t.object("TaskLease", {
  id: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  taskId: __t.string(),
  version: __t.u64(),
});
export type TaskLease = __Infer<typeof TaskLease>;

export const Thesis = __t.object("Thesis", {
  id: __t.string(),
  runId: __t.string(),
  symbol: __t.string(),
  author: __t.identity(),
  bullCase: __t.string(),
  bearCase: __t.string(),
  assumptions: __t.string(),
  invalidation: __t.string(),
  evidenceRefs: __t.string(),
  createdAt: __t.timestamp(),
  taskId: __t.string(),
});
export type Thesis = __Infer<typeof Thesis>;

export const TradeProposal = __t.object("TradeProposal", {
  id: __t.string(),
  runId: __t.string(),
  thesisId: __t.string(),
  symbol: __t.string(),
  side: __t.string(),
  quantity: __t.string(),
  orderType: __t.string(),
  limitPrice: __t.string(),
  status: __t.string(),
  proposedBy: __t.identity(),
  createdAt: __t.timestamp(),
});
export type TradeProposal = __Infer<typeof TradeProposal>;

