// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AccountSnapshot = __t.object("AccountSnapshot", {
  id: __t.string(),
  cash: __t.string(),
  buyingPower: __t.string(),
  equity: __t.string(),
  positionsRef: __t.string(),
  openOrdersRef: __t.string(),
  capturedAt: __t.timestamp(),
});
export type AccountSnapshot = __Infer<typeof AccountSnapshot>;

export const Agent = __t.object("Agent", {
  identity: __t.identity(),
  role: __t.string(),
  status: __t.string(),
  lastSeen: __t.timestamp(),
});
export type Agent = __Infer<typeof Agent>;

export const Approval = __t.object("Approval", {
  proposalId: __t.string(),
  approver: __t.identity(),
  riskDecisionId: __t.string(),
  approvedAt: __t.timestamp(),
});
export type Approval = __Infer<typeof Approval>;

export const Decision = __t.object("Decision", {
  id: __t.string(),
  thesisId: __t.string(),
  reviewer: __t.identity(),
  outcome: __t.string(),
  rationale: __t.string(),
  createdAt: __t.timestamp(),
});
export type Decision = __Infer<typeof Decision>;

export const Fact = __t.object("Fact", {
  id: __t.string(),
  sourceId: __t.string(),
  symbol: __t.string(),
  metric: __t.string(),
  value: __t.string(),
  unit: __t.string(),
  period: __t.string(),
  quality: __t.string(),
  createdAt: __t.timestamp(),
});
export type Fact = __Infer<typeof Fact>;

export const Fill = __t.object("Fill", {
  id: __t.string(),
  orderId: __t.string(),
  alpacaActivityId: __t.string(),
  quantity: __t.string(),
  price: __t.string(),
  filledAt: __t.timestamp(),
});
export type Fill = __Infer<typeof Fill>;

export const Message = __t.object("Message", {
  id: __t.string(),
  runId: __t.string(),
  taskId: __t.string(),
  sender: __t.identity(),
  kind: __t.string(),
  body: __t.string(),
  evidenceRef: __t.string(),
  createdAt: __t.timestamp(),
});
export type Message = __Infer<typeof Message>;

export const OwnerConfig = __t.object("OwnerConfig", {
  key: __t.string(),
  owner: __t.identity(),
});
export type OwnerConfig = __Infer<typeof OwnerConfig>;

export const PaperOrder = __t.object("PaperOrder", {
  id: __t.string(),
  proposalId: __t.string(),
  clientOrderId: __t.string(),
  alpacaOrderId: __t.string(),
  status: __t.string(),
  submittedAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type PaperOrder = __Infer<typeof PaperOrder>;

export const Reconciliation = __t.object("Reconciliation", {
  id: __t.string(),
  status: __t.string(),
  details: __t.string(),
  capturedAt: __t.timestamp(),
});
export type Reconciliation = __Infer<typeof Reconciliation>;

export const RiskDecision = __t.object("RiskDecision", {
  id: __t.string(),
  proposalId: __t.string(),
  reviewer: __t.identity(),
  policyVersion: __t.string(),
  outcome: __t.string(),
  checks: __t.string(),
  decidedAt: __t.timestamp(),
  expiresAt: __t.timestamp(),
});
export type RiskDecision = __Infer<typeof RiskDecision>;

export const Run = __t.object("Run", {
  id: __t.string(),
  goal: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp(),
});
export type Run = __Infer<typeof Run>;

export const RunMetric = __t.object("RunMetric", {
  id: __t.string(),
  runId: __t.string(),
  name: __t.string(),
  value: __t.string(),
  observedAt: __t.timestamp(),
});
export type RunMetric = __Infer<typeof RunMetric>;

export const Source = __t.object("Source", {
  id: __t.string(),
  runId: __t.string(),
  symbol: __t.string(),
  kind: __t.string(),
  uri: __t.string(),
  asOf: __t.timestamp(),
  retrievedAt: __t.timestamp(),
  checksum: __t.string(),
  artifactRef: __t.string(),
});
export type Source = __Infer<typeof Source>;

export const Task = __t.object("Task", {
  id: __t.string(),
  runId: __t.string(),
  symbol: __t.string(),
  kind: __t.string(),
  objective: __t.string(),
  status: __t.string(),
  assignee: __t.option(__t.identity()),
  leaseUntil: __t.option(__t.timestamp()),
  version: __t.u64(),
  result: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Task = __Infer<typeof Task>;

export const TaskLease = __t.object("TaskLease", {
  id: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  taskId: __t.string(),
  version: __t.u64(),
});
export type TaskLease = __Infer<typeof TaskLease>;

export const Thesis = __t.object("Thesis", {
  id: __t.string(),
  runId: __t.string(),
  symbol: __t.string(),
  author: __t.identity(),
  bullCase: __t.string(),
  bearCase: __t.string(),
  assumptions: __t.string(),
  invalidation: __t.string(),
  evidenceRefs: __t.string(),
  createdAt: __t.timestamp(),
});
export type Thesis = __Infer<typeof Thesis>;

export const TradeProposal = __t.object("TradeProposal", {
  id: __t.string(),
  runId: __t.string(),
  thesisId: __t.string(),
  symbol: __t.string(),
  side: __t.string(),
  quantity: __t.string(),
  orderType: __t.string(),
  limitPrice: __t.string(),
  status: __t.string(),
  proposedBy: __t.identity(),
  createdAt: __t.timestamp(),
});
export type TradeProposal = __Infer<typeof TradeProposal>;
