// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import BeginActionReducer from "../begin_action_reducer";
import BeginInferenceReducer from "../begin_inference_reducer";
import ConfigureSpendReducer from "../configure_spend_reducer";
import CreateRunReducer from "../create_run_reducer";
import FinishActionReducer from "../finish_action_reducer";
import FinishInferenceReducer from "../finish_inference_reducer";
import GrantMemberReducer from "../grant_member_reducer";
import GrantOperatorReducer from "../grant_operator_reducer";
import PostMessageReducer from "../post_message_reducer";
import PublishKnowledgeReducer from "../publish_knowledge_reducer";
import PublishStateReducer from "../publish_state_reducer";
import ResolveActionReducer from "../resolve_action_reducer";
import ResolveInferenceReducer from "../resolve_inference_reducer";
import ReviewKnowledgeReducer from "../review_knowledge_reducer";
import RevokeMemberReducer from "../revoke_member_reducer";
import SetRunStatusReducer from "../set_run_status_reducer";

export type BeginActionParams = __Infer<typeof BeginActionReducer>;
export type BeginInferenceParams = __Infer<typeof BeginInferenceReducer>;
export type ConfigureSpendParams = __Infer<typeof ConfigureSpendReducer>;
export type CreateRunParams = __Infer<typeof CreateRunReducer>;
export type FinishActionParams = __Infer<typeof FinishActionReducer>;
export type FinishInferenceParams = __Infer<typeof FinishInferenceReducer>;
export type GrantMemberParams = __Infer<typeof GrantMemberReducer>;
export type GrantOperatorParams = __Infer<typeof GrantOperatorReducer>;
export type PostMessageParams = __Infer<typeof PostMessageReducer>;
export type PublishKnowledgeParams = __Infer<typeof PublishKnowledgeReducer>;
export type PublishStateParams = __Infer<typeof PublishStateReducer>;
export type ResolveActionParams = __Infer<typeof ResolveActionReducer>;
export type ResolveInferenceParams = __Infer<typeof ResolveInferenceReducer>;
export type ReviewKnowledgeParams = __Infer<typeof ReviewKnowledgeReducer>;
export type RevokeMemberParams = __Infer<typeof RevokeMemberReducer>;
export type SetRunStatusParams = __Infer<typeof SetRunStatusReducer>;
