// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  path: __t.string().primaryKey(),
  holder: __t.string(),
  taskId: __t.string().name("task_id"),
  reason: __t.string(),
  acquiredAt: __t.timestamp().name("acquired_at"),
  expiresAt: __t.timestamp().name("expires_at"),
});
