// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ArchivedTask = __t.object("ArchivedTask", {
  id: __t.string(),
  title: __t.string(),
  details: __t.string(),
  area: __t.string(),
  status: __t.string(),
  createdBy: __t.string(),
  assignee: __t.string(),
  dependsOn: __t.string(),
  result: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type ArchivedTask = __Infer<typeof ArchivedTask>;

export const BoardConfig = __t.object("BoardConfig", {
  key: __t.string(),
  participantLimit: __t.u32(),
});
export type BoardConfig = __Infer<typeof BoardConfig>;

export const BoardOperator = __t.object("BoardOperator", {
  key: __t.string(),
  identity: __t.identity(),
});
export type BoardOperator = __Infer<typeof BoardOperator>;

export const DevMessage = __t.object("DevMessage", {
  id: __t.u64(),
  sender: __t.string(),
  recipient: __t.string(),
  taskId: __t.string(),
  body: __t.string(),
  createdAt: __t.timestamp(),
});
export type DevMessage = __Infer<typeof DevMessage>;

export const DevTask = __t.object("DevTask", {
  id: __t.string(),
  title: __t.string(),
  details: __t.string(),
  area: __t.string(),
  status: __t.string(),
  createdBy: __t.string(),
  assignee: __t.string(),
  dependsOn: __t.string(),
  result: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type DevTask = __Infer<typeof DevTask>;

export const FileLock = __t.object("FileLock", {
  path: __t.string(),
  holder: __t.string(),
  taskId: __t.string(),
  reason: __t.string(),
  acquiredAt: __t.timestamp(),
  expiresAt: __t.timestamp(),
});
export type FileLock = __Infer<typeof FileLock>;

export const Session = __t.object("Session", {
  name: __t.string(),
  tool: __t.string(),
  focus: __t.string(),
  lastSeen: __t.timestamp(),
});
export type Session = __Infer<typeof Session>;

export const SessionIdentity = __t.object("SessionIdentity", {
  name: __t.string(),
  identity: __t.identity(),
});
export type SessionIdentity = __Infer<typeof SessionIdentity>;

export const TaskPriority = __t.object("TaskPriority", {
  taskId: __t.string(),
  priority: __t.string(),
  updatedBy: __t.string(),
  updatedAt: __t.timestamp(),
});
export type TaskPriority = __Infer<typeof TaskPriority>;
