// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddFactReducer from "../add_fact_reducer";
import AddSourceReducer from "../add_source_reducer";
import ApproveProposalReducer from "../approve_proposal_reducer";
import ClaimTaskReducer from "../claim_task_reducer";
import CompleteTaskReducer from "../complete_task_reducer";
import CreateRunReducer from "../create_run_reducer";
import CreateTaskReducer from "../create_task_reducer";
import FailTaskReducer from "../fail_task_reducer";
import GrantAgentReducer from "../grant_agent_reducer";
import HeartbeatReducer from "../heartbeat_reducer";
import PostMessageReducer from "../post_message_reducer";
import ProposeTradeReducer from "../propose_trade_reducer";
import PublishThesisReducer from "../publish_thesis_reducer";
import RecordAccountSnapshotReducer from "../record_account_snapshot_reducer";
import RecordDecisionReducer from "../record_decision_reducer";
import RecordFillReducer from "../record_fill_reducer";
import RecordMarketObservationReducer from "../record_market_observation_reducer";
import RecordReconciliationReducer from "../record_reconciliation_reducer";
import RecordRiskDecisionReducer from "../record_risk_decision_reducer";
import RecordRunMetricReducer from "../record_run_metric_reducer";
import RenewTaskLeaseReducer from "../renew_task_lease_reducer";
import ReservePaperOrderReducer from "../reserve_paper_order_reducer";
import RevokeAgentReducer from "../revoke_agent_reducer";
import SetRunStatusReducer from "../set_run_status_reducer";
import UpdatePaperOrderReducer from "../update_paper_order_reducer";

export type AddFactParams = __Infer<typeof AddFactReducer>;
export type AddSourceParams = __Infer<typeof AddSourceReducer>;
export type ApproveProposalParams = __Infer<typeof ApproveProposalReducer>;
export type ClaimTaskParams = __Infer<typeof ClaimTaskReducer>;
export type CompleteTaskParams = __Infer<typeof CompleteTaskReducer>;
export type CreateRunParams = __Infer<typeof CreateRunReducer>;
export type CreateTaskParams = __Infer<typeof CreateTaskReducer>;
export type FailTaskParams = __Infer<typeof FailTaskReducer>;
export type GrantAgentParams = __Infer<typeof GrantAgentReducer>;
export type HeartbeatParams = __Infer<typeof HeartbeatReducer>;
export type PostMessageParams = __Infer<typeof PostMessageReducer>;
export type ProposeTradeParams = __Infer<typeof ProposeTradeReducer>;
export type PublishThesisParams = __Infer<typeof PublishThesisReducer>;
export type RecordAccountSnapshotParams = __Infer<typeof RecordAccountSnapshotReducer>;
export type RecordDecisionParams = __Infer<typeof RecordDecisionReducer>;
export type RecordFillParams = __Infer<typeof RecordFillReducer>;
export type RecordMarketObservationParams = __Infer<typeof RecordMarketObservationReducer>;
export type RecordReconciliationParams = __Infer<typeof RecordReconciliationReducer>;
export type RecordRiskDecisionParams = __Infer<typeof RecordRiskDecisionReducer>;
export type RecordRunMetricParams = __Infer<typeof RecordRunMetricReducer>;
export type RenewTaskLeaseParams = __Infer<typeof RenewTaskLeaseReducer>;
export type ReservePaperOrderParams = __Infer<typeof ReservePaperOrderReducer>;
export type RevokeAgentParams = __Infer<typeof RevokeAgentReducer>;
export type SetRunStatusParams = __Infer<typeof SetRunStatusReducer>;
export type UpdatePaperOrderParams = __Infer<typeof UpdatePaperOrderReducer>;

