// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddFactReducer from "../add_fact_reducer";
import AddRiskPolicyReducer from "../add_risk_policy_reducer";
import AddSourceReducer from "../add_source_reducer";
import ApproveProposalReducer from "../approve_proposal_reducer";
import BeginInferenceReducer from "../begin_inference_reducer";
import BeginPaperSubmissionReducer from "../begin_paper_submission_reducer";
import ClaimTaskReducer from "../claim_task_reducer";
import CompleteTaskReducer from "../complete_task_reducer";
import ConfigureRunLimitsReducer from "../configure_run_limits_reducer";
import CreateRunReducer from "../create_run_reducer";
import CreateTaskReducer from "../create_task_reducer";
import FailTaskReducer from "../fail_task_reducer";
import FinishInferenceReducer from "../finish_inference_reducer";
import FinishPaperSubmissionReducer from "../finish_paper_submission_reducer";
import GrantAccountAccessReducer from "../grant_account_access_reducer";
import GrantAgentReducer from "../grant_agent_reducer";
import GrantRunAccessReducer from "../grant_run_access_reducer";
import HeartbeatReducer from "../heartbeat_reducer";
import PostMessageReducer from "../post_message_reducer";
import ProposeTradeReducer from "../propose_trade_reducer";
import PublishThesisReducer from "../publish_thesis_reducer";
import ReconcilePaperAccountReducer from "../reconcile_paper_account_reducer";
import RecordAccountSnapshotReducer from "../record_account_snapshot_reducer";
import RecordDecisionReducer from "../record_decision_reducer";
import RecordDecisionInputReducer from "../record_decision_input_reducer";
import RecordFillReducer from "../record_fill_reducer";
import RecordMarketClockReducer from "../record_market_clock_reducer";
import RecordReconciliationReducer from "../record_reconciliation_reducer";
import RecordRiskDecisionReducer from "../record_risk_decision_reducer";
import RecordRunMetricReducer from "../record_run_metric_reducer";
import RecordTradeDecisionReducer from "../record_trade_decision_reducer";
import RenewTaskLeaseReducer from "../renew_task_lease_reducer";
import RequestOrderCancelReducer from "../request_order_cancel_reducer";
import ReservePaperOrderReducer from "../reserve_paper_order_reducer";
import ResolveUncertainPaperIntentReducer from "../resolve_uncertain_paper_intent_reducer";
import RevokeAccountAccessReducer from "../revoke_account_access_reducer";
import RevokeAgentReducer from "../revoke_agent_reducer";
import RevokeRunAccessReducer from "../revoke_run_access_reducer";
import SetPaperAccountBaselineReducer from "../set_paper_account_baseline_reducer";
import SetRunStatusReducer from "../set_run_status_reducer";
import UpdateOrderCancelReducer from "../update_order_cancel_reducer";
import UpdatePaperOrderReducer from "../update_paper_order_reducer";

export type AddFactParams = __Infer<typeof AddFactReducer>;
export type AddRiskPolicyParams = __Infer<typeof AddRiskPolicyReducer>;
export type AddSourceParams = __Infer<typeof AddSourceReducer>;
export type ApproveProposalParams = __Infer<typeof ApproveProposalReducer>;
export type BeginInferenceParams = __Infer<typeof BeginInferenceReducer>;
export type BeginPaperSubmissionParams = __Infer<typeof BeginPaperSubmissionReducer>;
export type ClaimTaskParams = __Infer<typeof ClaimTaskReducer>;
export type CompleteTaskParams = __Infer<typeof CompleteTaskReducer>;
export type ConfigureRunLimitsParams = __Infer<typeof ConfigureRunLimitsReducer>;
export type CreateRunParams = __Infer<typeof CreateRunReducer>;
export type CreateTaskParams = __Infer<typeof CreateTaskReducer>;
export type FailTaskParams = __Infer<typeof FailTaskReducer>;
export type FinishInferenceParams = __Infer<typeof FinishInferenceReducer>;
export type FinishPaperSubmissionParams = __Infer<typeof FinishPaperSubmissionReducer>;
export type GrantAccountAccessParams = __Infer<typeof GrantAccountAccessReducer>;
export type GrantAgentParams = __Infer<typeof GrantAgentReducer>;
export type GrantRunAccessParams = __Infer<typeof GrantRunAccessReducer>;
export type HeartbeatParams = __Infer<typeof HeartbeatReducer>;
export type PostMessageParams = __Infer<typeof PostMessageReducer>;
export type ProposeTradeParams = __Infer<typeof ProposeTradeReducer>;
export type PublishThesisParams = __Infer<typeof PublishThesisReducer>;
export type ReconcilePaperAccountParams = __Infer<typeof ReconcilePaperAccountReducer>;
export type RecordAccountSnapshotParams = __Infer<typeof RecordAccountSnapshotReducer>;
export type RecordDecisionParams = __Infer<typeof RecordDecisionReducer>;
export type RecordDecisionInputParams = __Infer<typeof RecordDecisionInputReducer>;
export type RecordFillParams = __Infer<typeof RecordFillReducer>;
export type RecordMarketClockParams = __Infer<typeof RecordMarketClockReducer>;
export type RecordReconciliationParams = __Infer<typeof RecordReconciliationReducer>;
export type RecordRiskDecisionParams = __Infer<typeof RecordRiskDecisionReducer>;
export type RecordRunMetricParams = __Infer<typeof RecordRunMetricReducer>;
export type RecordTradeDecisionParams = __Infer<typeof RecordTradeDecisionReducer>;
export type RenewTaskLeaseParams = __Infer<typeof RenewTaskLeaseReducer>;
export type RequestOrderCancelParams = __Infer<typeof RequestOrderCancelReducer>;
export type ReservePaperOrderParams = __Infer<typeof ReservePaperOrderReducer>;
export type ResolveUncertainPaperIntentParams = __Infer<typeof ResolveUncertainPaperIntentReducer>;
export type RevokeAccountAccessParams = __Infer<typeof RevokeAccountAccessReducer>;
export type RevokeAgentParams = __Infer<typeof RevokeAgentReducer>;
export type RevokeRunAccessParams = __Infer<typeof RevokeRunAccessReducer>;
export type SetPaperAccountBaselineParams = __Infer<typeof SetPaperAccountBaselineReducer>;
export type SetRunStatusParams = __Infer<typeof SetRunStatusReducer>;
export type UpdateOrderCancelParams = __Infer<typeof UpdateOrderCancelReducer>;
export type UpdatePaperOrderParams = __Infer<typeof UpdatePaperOrderReducer>;

