// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ApplyPushPolicyReducer from "../apply_push_policy_reducer";
import ClaimTaskReducer from "../claim_task_reducer";
import CreateTaskReducer from "../create_task_reducer";
import LockReducer from "../lock_reducer";
import PostReducer from "../post_reducer";
import RegisterReducer from "../register_reducer";
import UnlockReducer from "../unlock_reducer";
import UpdateTaskReducer from "../update_task_reducer";

export type ApplyPushPolicyParams = __Infer<typeof ApplyPushPolicyReducer>;
export type ClaimTaskParams = __Infer<typeof ClaimTaskReducer>;
export type CreateTaskParams = __Infer<typeof CreateTaskReducer>;
export type LockParams = __Infer<typeof LockReducer>;
export type PostParams = __Infer<typeof PostReducer>;
export type RegisterParams = __Infer<typeof RegisterReducer>;
export type UnlockParams = __Infer<typeof UnlockReducer>;
export type UpdateTaskParams = __Infer<typeof UpdateTaskReducer>;

