// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  runId: __t.string().name("run_id"),
  actor: __t.identity(),
  reservedTokens: __t.u32().name("reserved_tokens"),
  tokensUsed: __t.u32().name("tokens_used"),
  status: __t.string(),
  model: __t.string(),
  outputJson: __t.string().name("output_json"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
  workId: __t.string().name("work_id"),
  inputHash: __t.string().name("input_hash"),
});
