// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  version: __t.string(),
  model: __t.string(),
  inputMicrosPerMillion: __t.u64().name("input_micros_per_million"),
  cacheReadMicrosPerMillion: __t.u64().name("cache_read_micros_per_million"),
  cacheWriteMicrosPerMillion: __t.u64().name("cache_write_micros_per_million"),
  outputMicrosPerMillion: __t.u64().name("output_micros_per_million"),
  createdAt: __t.timestamp().name("created_at"),
});
