// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  status: __t.string(),
  goal: __t.string(),
  mode: __t.string(),
  maxCalls: __t.u32().name("max_calls"),
  maxTokens: __t.u32().name("max_tokens"),
  maxConcurrent: __t.u32().name("max_concurrent"),
  usedCalls: __t.u32().name("used_calls"),
  usedTokens: __t.u32().name("used_tokens"),
  pricingVersion: __t.string().name("pricing_version"),
  maxSpendMicros: __t.u64().name("max_spend_micros"),
  maxWorkerSpendMicros: __t.u64().name("max_worker_spend_micros"),
  usedSpendMicros: __t.u64().name("used_spend_micros"),
  createdAt: __t.timestamp().name("created_at"),
});
