// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const GameAction = __t.object("GameAction", {
  id: __t.string(),
  runId: __t.string(),
  actor: __t.identity(),
  commandJson: __t.string(),
  refs: __t.string(),
  status: __t.string(),
  result: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type GameAction = __Infer<typeof GameAction>;

export const GameInference = __t.object("GameInference", {
  id: __t.string(),
  runId: __t.string(),
  actor: __t.identity(),
  reservedTokens: __t.u32(),
  tokensUsed: __t.u32(),
  status: __t.string(),
  model: __t.string(),
  outputJson: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  workId: __t.string(),
  inputHash: __t.string(),
});
export type GameInference = __Infer<typeof GameInference>;

export const GameKnowledge = __t.object("GameKnowledge", {
  id: __t.string(),
  runId: __t.string(),
  author: __t.identity(),
  label: __t.string(),
  x: __t.f64(),
  y: __t.f64(),
  z: __t.f64(),
  state: __t.string(),
  updatedAt: __t.timestamp(),
});
export type GameKnowledge = __Infer<typeof GameKnowledge>;

export const GameMember = __t.object("GameMember", {
  id: __t.string(),
  runId: __t.string(),
  identity: __t.identity(),
  name: __t.string(),
  role: __t.string(),
  stateJson: __t.string(),
  updatedAt: __t.timestamp(),
});
export type GameMember = __Infer<typeof GameMember>;

export const GameMessage = __t.object("GameMessage", {
  id: __t.string(),
  runId: __t.string(),
  sender: __t.identity(),
  recipient: __t.string(),
  kind: __t.string(),
  body: __t.string(),
  createdAt: __t.timestamp(),
});
export type GameMessage = __Infer<typeof GameMessage>;

export const GameOwner = __t.object("GameOwner", {
  id: __t.string(),
  identity: __t.identity(),
});
export type GameOwner = __Infer<typeof GameOwner>;

export const GameRun = __t.object("GameRun", {
  id: __t.string(),
  status: __t.string(),
  goal: __t.string(),
  mode: __t.string(),
  maxCalls: __t.u32(),
  maxTokens: __t.u32(),
  maxConcurrent: __t.u32(),
  usedCalls: __t.u32(),
  usedTokens: __t.u32(),
  createdAt: __t.timestamp(),
});
export type GameRun = __Infer<typeof GameRun>;

export const MyAction = __t.object("MyAction", {});
export type MyAction = __Infer<typeof MyAction>;

export const MyInference = __t.object("MyInference", {});
export type MyInference = __Infer<typeof MyInference>;

export const MyKnowledge = __t.object("MyKnowledge", {});
export type MyKnowledge = __Infer<typeof MyKnowledge>;

export const MyMember = __t.object("MyMember", {});
export type MyMember = __Infer<typeof MyMember>;

export const MyMessage = __t.object("MyMessage", {});
export type MyMessage = __Infer<typeof MyMessage>;

export const MyRun = __t.object("MyRun", {});
export type MyRun = __Infer<typeof MyRun>;

